baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Debaditya Tech Journal"
theme = "hugo-theme-learn"
themesdir = "/themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  description = "Debaditya Tech Journal"
  author = "Debaditya Chakravorty"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Debaditya Tech Journal"
weight = 1
languageName = "English"


[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
url = "https://github.com/debaditc"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-atom'></i> Hobby Projects"
url = "/showcase"
weight = 21

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Linkedin"
url = "https://www.linkedin.com/in/debaditya-chakravorty/"
weight = 15

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30

[deployment]
[[deployment.targets]]
name = "s3 target"
URL = "s3://techvidyarthi.com?region=us-east-1"